### ISSUE TITLE
mkdir errors

### ISSUE THREAD

**Issue by nchernia** [eudoraleer/scasa#1]
Hello,

I'm trying to run your tool and can't get it to work. I was running in "already aligned" mode since salmon alevin has already been run. However it can't get beyond the below. These directories do not exist before executing the command.

```
scasa --postalign_dir salmon/ --align NO --quant NO --in cDNA/ --fastq test_R1.gz,test_R2.gz --ref reference/gencode.v34.transcripts.fa --out /mnt/disks/big_data/calico/scasa

##############################################################
#	SCASA V1.0.0
#	SINGLE CELL TRANSCRIPT QUANTIFICATION TOOL
#	Version Date: 2021-04-07
#	FOR ANY ISSUES, CONTACT: LU.PAN@KI.SE
#	https://github.com/eudoraleer/scasa/
##############################################################

Directory scasa already exists. Writing into existing directory..
mkdir: cannot create directory ‘scasa/SCASA_My_Project_20220321141047/’: File exists
All done!
```

Even on your tutorial example, there are similar errors, but it keeps going:

```
mkdir: cannot create directory ‘Scasa_out/SCASA_My_Project_20220321143943/’: File exists

Preparing for alignment..
Indexing reference..
Directory Scasa_out/SCASA_My_Project_20220321143943/0PRESETS//REF_INDEX/ already exists. Writing into existing directory..
```

**Comment by nchernia** [comment]
Tutorial examples halts with errors.

`Finnished indexing reference..
Begins pseudo-alignment..
nohup: redirecting stderr to stdout
Congratulations! Pseudo-alignment has completed in 30 seconds!
Scasa quantification has started..
Begin Scasa quantification for sample Sample_01_S1_L001..
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in FUN(X[[i]], ...) :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in FUN(X[[i]], ...) : unable to install packages
Calls: lapply -> FUN
Execution halted
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in FUN(X[[i]], ...) :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in FUN(X[[i]], ...) : unable to install packages
Calls: lapply -> FUN
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'Scasa_out/SCASA_My_Project_20220321143943/2QUANT//Sample_01_S1_L001_quant//scasa_isoform_expression.RData', probable reason 'No such file or directory'
Execution halted
Congratulations! Scasa single cell RNA-Seq transcript quantification has completed in 30 seconds!
All done!
`

**Comment by eudoraleer** [comment]
> Hello,
> 
> I'm trying to run your tool and can't get it to work. I was running in "already aligned" mode since salmon alevin has already been run. However it can't get beyond the below. These directories do not exist before executing the command.
> 
> ```
> scasa --postalign_dir salmon/ --align NO --quant NO --in cDNA/ --fastq test_R1.gz,test_R2.gz --ref reference/gencode.v34.transcripts.fa --out /mnt/disks/big_data/calico/scasa
> 
> ##############################################################
> #	SCASA V1.0.0
> #	SINGLE CELL TRANSCRIPT QUANTIFICATION TOOL
> #	Version Date: 2021-04-07
> #	FOR ANY ISSUES, CONTACT: LU.PAN@KI.SE
> #	https://github.com/eudoraleer/scasa/
> ##############################################################
> 
> Directory scasa already exists. Writing into existing directory..
> mkdir: cannot create directory ‘scasa/SCASA_My_Project_20220321141047/’: File exists
> All done!
> ```
> 
> Even on your tutorial example, there are similar errors, but it keeps going:
> 
> ```
> mkdir: cannot create directory ‘Scasa_out/SCASA_My_Project_20220321143943/’: File exists
> 
> Preparing for alignment..
> Indexing reference..
> Directory Scasa_out/SCASA_My_Project_20220321143943/0PRESETS//REF_INDEX/ already exists. Writing into existing directory..
> ```

Hi nchernia,

Thank you for submitting the question! Basically, Scasa is a quantification tool, if you set --align to NO and --quant to NO, which means no alignment will be done and no quantification will be done, i.e. you do not want scasa to do anything, so nothing would be done. Another thing is, for all the paths you need to provide, it has to be in full path, i.e. if you provide a path in the current directory for example, you need to specify from root, for example, a path to the fasta reference file: /mnt/example/new/reference_file_name.gz

I have fixed some bugs along the way too, thank you for pointing out the error, could you try again and let me know if if works?

Best,
Lu

**Comment by eudoraleer** [comment]
> Tutorial examples halts with errors.
> 
> `Finnished indexing reference.. Begins pseudo-alignment.. nohup: redirecting stderr to stdout Congratulations! Pseudo-alignment has completed in 30 seconds! Scasa quantification has started.. Begin Scasa quantification for sample Sample_01_S1_L001.. Installing package into ‘/usr/local/lib/R/site-library’ (as ‘lib’ is unspecified) Warning in FUN(X[[i]], ...) : 'lib = "/usr/local/lib/R/site-library"' is not writable Error in FUN(X[[i]], ...) : unable to install packages Calls: lapply -> FUN Execution halted Installing package into ‘/usr/local/lib/R/site-library’ (as ‘lib’ is unspecified) Warning in FUN(X[[i]], ...) : 'lib = "/usr/local/lib/R/site-library"' is not writable Error in FUN(X[[i]], ...) : unable to install packages Calls: lapply -> FUN Execution halted Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection Calls: load -> readChar In addition: Warning message: In readChar(con, 5L, useBytes = TRUE) : cannot open compressed file 'Scasa_out/SCASA_My_Project_20220321143943/2QUANT//Sample_01_S1_L001_quant//scasa_isoform_expression.RData', probable reason 'No such file or directory' Execution halted Congratulations! Scasa single cell RNA-Seq transcript quantification has completed in 30 seconds! All done! `

Some of the R packages are needed for using Scasa, but it seems that the packages have no permission to get install in the default directory, another way is that, you could try installing the package dependencies before using scasa:

library(GenomicFeatures)
library(Biostrings)
library(polyester)
library(foreach)
library(doParallel)
library(data.table)
library(plyr)
